# Workflow for building and testing docs
##
name: Build docs before merging

on:
  # Runs on pushes targeting the release branch
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Type check
        run: yarn typecheck
      - name: Build with docusaurus
        run: yarn build
